
function m2n(note) {
    return (note).replace("21", "A0")
        .replace("22", "Bb0")
        .replace("23", "B0")
        //---------------------
        .replace("24", "C1")
        .replace("25", "Cs1")
        .replace("26", "D1")
        .replace("27", "Ds1")
        .replace("28", "E1")
        .replace("29", "F1")
        .replace("30", "Fs1")
        .replace("31", "G1")
        .replace("32", "Gs1")
        .replace("33", "A1")
        .replace("34", "Bb1")
        .replace("35", "B1")
        //---------------------
        .replace("36", "C2")
        .replace("37", "Cs2")
        .replace("38", "D2")
        .replace("39", "Ds2")
        .replace("40", "E2")
        .replace("41", "F2")
        .replace("42", "Fs2")
        .replace("43", "G2")
        .replace("44", "Gs2")
        .replace("45", "A2")
        .replace("46", "Bb2")
        .replace("47", "B2")
        //---------------------
        .replace("48", "C3")
        .replace("49", "Cs3")
        .replace("50", "D3")
        .replace("51", "Ds3")
        .replace("52", "E3")
        .replace("53", "F3")
        .replace("54", "Fs3")
        .replace("55", "G3")
        .replace("56", "Gs3")
        .replace("57", "A3")
        .replace("58", "Bb3")
        .replace("59", "B3")
        //---------------------
        .replace("60", "C4")
        .replace("61", "Cs4")
        .replace("62", "D4")
        .replace("63", "Ds4")
        .replace("64", "E4")
        .replace("65", "F4")
        .replace("66", "Fs4")
        .replace("67", "G4")
        .replace("68", "Gs4")
        .replace("69", "A4")
        .replace("70", "Bb4")
        .replace("71", "B4")
        //---------------------
        .replace("72", "C5")
        .replace("73", "Cs5")
        .replace("74", "D5")
        .replace("75", "Ds5")
        .replace("76", "E5")
        .replace("77", "F5")
        .replace("78", "Fs5")
        .replace("79", "G5")
        .replace("80", "Gs5")
        .replace("81", "A5")
        .replace("82", "Bb5")
        .replace("83", "B5")
        //---------------------
        .replace("84", "C6")
        .replace("85", "Cs6")
        .replace("86", "D6")
        .replace("87", "Ds6")
        .replace("88", "E6")
        .replace("89", "F6")
        .replace("90", "Fs6")
        .replace("91", "G6")
        .replace("92", "Gs6")
        .replace("93", "A6")
        .replace("94", "Bb6")
        .replace("95", "B6")
        //---------------------
        .replace("96", "C7")
        .replace("97", "Cs7")
        .replace("98", "D7")
        .replace("99", "Ds7")
        .replace("100", "E7")
        .replace("101", "F7")
        .replace("102", "Fs7")
        .replace("103", "G7")
        .replace("104", "Gs7")
        .replace("105", "A7")
        .replace("106", "Bb7")
        .replace("107", "B7")
        //---------------------
        .replace("108", "C8")

        .replace("", "")

}